on: [ workflow_call ]
jobs:
  Release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.ref }}
    - run: |
        echo '${{ vars.RELEASE_SIGNERS }}' > ./allowed_signers
        git config gpg.ssh.allowedSignersFile ./allowed_signers
        git verify-tag -v ${{ github.ref_name }}
      name: Verify release tag signature
    - uses: actions/setup-node@v5
      with:
        registry-url: https://registry.npmjs.org/
    - run: |
        MSG=$(git log -1 --no-show-signature --format=%B $TAG)
        TITLE=$(echo "$MSG" | head -n 1)
        NOTES=$(echo "$MSG" | tail -n +2)
        gh release create $TAG --title "$TITLE" --notes "$NOTES"
        [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo "PUBLISH=latest" >> $GITHUB_ENV || echo "PUBLISH=next" >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ github.token }}
        TAG: ${{ github.ref_name }}
    - run: npm publish --provenance --access public --tag $PUBLISH

